export const TOGGLE_MODAL_SUSCRIPTION = "TOGGLE_MODAL_SUSCRIPTION"
export const TOGGLE_MODAL_UPDATE_USER_INFO = "TOGGLE_MODAL_UPDATE_USER_INFO"
export const TOGGLE_MODAL_ADDING_FAQS = "TOGGLE_MODAL_ADDING_FAQS"